### ISSUE TITLE
Associated Features - Skin

### ISSUE THREAD

**Issue by ktuwh** [HL7/fhir-breast-radiology-ig#59]
Some items are listed as different things. The skin retraction and skin thickening are associated features for MRSYS, but PenRad is an associated feature value set. An observed feature is an associated feature. It can be both a finding and an associated feature. An architectural distortion can be a finding that as an associated feature that has an architectural distortion.

**Comment by Gjoll** [comment]
Associated Features has been made a single class, with a codeable concept list for the type. Architectural Distoration is just a code if found in an associated feature, but is a full resource if it is its own abnormality.
