### ISSUE TITLE
Architectural Feature or Distortion

### ISSUE THREAD

**Issue by ktuwh** [HL7/fhir-breast-radiology-ig#60]
o	A mass is listed as an architectural distortion. The thickening and mass are just clicks. If it is an architectural distortion is listed as a finding. An architectural distortion should just be a feature. Kurt will check to see if PenRad does this the same way that MRSYS does. 
o	Is a classification there or not? An architectural distortion finding needs no further definition for MRSYS. Thickening can be done this way as well. If PenRad went with this, an associated architectural feature would just be an observed feature set. Calcification, architectural distortion and mass need to be added to this area. Kurt will check with Greg as this seems as a loop and not a singular item that is described. 
o	The ultrasound, under the MRI, there is distribution with several options. If there are some items that are just under ultrasound and MRI, should be their own class? Kurt has only placeholders for MRI and ultrasound. 
	Focal
	Linear
	Segmental
	Regional
	Multiple Regions
	Diffuse
Greg has different patterns for this. Kurt made them separate patterns. These only appear for some of the findings, but not all. These do not appear on every ultrasound finding. An echo pattern has more to do with distribution. This is particularly with elasticity. One or more of these values can be used regarding the structure. It may be good to split them out.

**Comment by Gjoll** [comment]
Penrad does this the same as MRS.
