### ISSUE TITLE
Mammograms - Micro Labulated

### ISSUE THREAD

**Issue by ktuwh** [HL7/fhir-breast-radiology-ig#61]
Micro lobulated is the same as lobulated? Is it the same as architectural distortion? An abnormality cyst can be associated with it. The abnormality value of cysts could have a code or a descriptor of the total class. It is just a normal cyst. A cyst appears for PenRad under mammography. MRSYS has this listed under ultrasound and potentially nuclear medicine.

**Comment by Gjoll** [comment]
Duplicatre issue
