### ISSUE TITLE
Are mass and lesion the same?

### ISSUE THREAD

**Issue by ktuwh** [HL7/fhir-breast-radiology-ig#66]
Are a mass and a lesion the same? There are some people who prefer not to use the term ‘mass’. This is because ‘mass’ is considered malignant. Lesion is usually used as benign. There is not a fat containing lesion listed. Maybe a new fat containing mass type? Is fat containing considered partially solid?

A Dr. Mike question??

**Comment by Gjoll** [comment]
They are treated the same here *i,e. mass)
